name = "HTSTEM SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "413d8ef11eb0c4b8072f106b5ba3f29eb664ccdbe0077b13dfa492476216e24a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
unsup = "0.2.0"

[options]
datapack-folder = "config/paxi/datapacks"
