name = "HTSTEM SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf8bb4c652086308ec7f3e720fff845b9ba9d8071cc89b1b8f0e6206c8e6432d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
unsup = "0.2.0"

[options]
datapack-folder = "config/paxi/datapacks"
