name = "HTSTEM SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93b7417b104a4b8c3fc84c2cd0a275d93294e407ee6a02f298bf574fae631484"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
unsup = "0.2.0"

[options]
datapack-folder = "config/paxi/datapacks"
