name = "HTSTEM SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdd3d55b8cf25b5b51eccef342f977acc46f526adefa5697a67fcfd029b69420"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
unsup = "0.2.0"

[options]
datapack-folder = "config/paxi/datapacks"
