name = "HTSTEM SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c00fa40c15bda514d62f55ade0032d7744574fcc18d952255941f0abb27ebf0"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
unsup = "0.2.0"

[options]
datapack-folder = "config/paxi/datapacks"
